### ISSUE TITLE
nil error

### ISSUE THREAD

**Issue by mcandre** [fulldecent/structured-acceptance-test#42]
I merged a PR supposedly adding structured-acceptance-test support to my project, but now I get a nil error:

```console
$ cucumber
Feature: Run example tests

  Scenario: Running example tests            # features/run_example_tests.feature:2
/Users/andrew/.gem/ruby/2.3.7/gems/structured-acceptance-test-0.0.6/lib/finding.rb:57:in `block in categories=': undefined method `include?' for nil:NilClass (NoMethodError)
	from /Users/andrew/.gem/ruby/2.3.7/gems/structured-acceptance-test-0.0.6/lib/finding.rb:55:in `each'
	from /Users/andrew/.gem/ruby/2.3.7/gems/structured-acceptance-test-0.0.6/lib/finding.rb:55:in `categories='
	from /Users/andrew/go/src/github.com/mcandre/cowl/lib/cowl.rb:88:in `to_finding'
	from /Users/andrew/go/src/github.com/mcandre/cowl/lib/cowl.rb:152:in `block in check'
	from /Users/andrew/go/src/github.com/mcandre/cowl/lib/cowl.rb:151:in `each'
	from /Users/andrew/go/src/github.com/mcandre/cowl/lib/cowl.rb:151:in `check'
	from /Users/andrew/go/src/github.com/mcandre/cowl/bin/cowl:72:in `block in main'
	from /Users/andrew/go/src/github.com/mcandre/cowl/bin/cowl:58:in `each'
	from /Users/andrew/go/src/github.com/mcandre/cowl/bin/cowl:58:in `main'
	from /Users/andrew/go/src/github.com/mcandre/cowl/bin/cowl:100:in `<top (required)>'
	from /Users/andrew/.gem/ruby/2.3.7/bin/cowl:23:in `load'
	from /Users/andrew/.gem/ruby/2.3.7/bin/cowl:23:in `<main>'
    Given the program has finished           # features/step_definitions/steps.rb:1
    Then the output is correct for each test # features/step_definitions/steps.rb:12
      
      expected: true
           got: false
      
      (compared using ==)
       (RSpec::Expectations::ExpectationNotMetError)
      features/run_example_tests.feature:4:in `Then the output is correct for each test'

Failing Scenarios:
cucumber features/run_example_tests.feature:2 # Scenario: Running example tests

1 scenario (1 failed)
2 steps (1 failed, 1 passed)
```

**Comment by fulldecent** [comment]
Thank you for reporting. I am not an expert on the Ruby implementation. Has anybody else here used this and can you please comment?
